package rialo:venus-sms@0.1.0;

use rialo:primitives@0.1.0.{pubkey, lamports, timestamp, error};

world venus-sms {
    export read-result: func() -> result<_, error>;
    export start: func(relay-url: string, payload: string) -> result<_, error>;
}
